version: '3'
services:
  event-store:
    image: docker.io/thenativeweb/eventsourcingdb:1.0.2
    user: "root:root"
    command: "run --api-token secret --data-directory-temporary --http-enabled=true --https-enabled=false --with-ui"
    ports:
      - "3000:3000"

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"