# DataSource Configuration
esdb:
  server:
    uri: http://localhost:3000
    api-token: secret
spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create-drop

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

# Flyway Configuration
  flyway:
    url: jdbc:postgresql://localhost:5432/postgres
    locations: classpath:db/migration
    user: postgres
    password: postgres
  docker:
    compose:
      enabled: true
      file: docker-compose.yml

application:
  debug:
    enabled: true
